apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-v1
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: temkaxd96/petclinic
        name: petclinic
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 3
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
          initialDelaySeconds: 10
    #   volumeMounts:
    #     - name: config
    #       mountPath: /opt
    # volumes:
    # - name: config
    #   configMap:
    #     name: configmap-petclinic
